#!/bin/sh

set -e

if [ ! -f /usr/cbin/tailscale ]; then
    arch=`uname -m`
    if [ "$arch" == "mips" ]; then
        endianness=`echo -n I | hexdump -o | awk '{ print (substr($2,6,1)=="1") ? "le" : ""; exit }'`
    elif [ "$arch" == "armv7l" ]; then
        arch=arm
    elif [ "$arch" == "aarch64" ]; then
        arch=arm64
    elif [ "$arch" == "x86_64" ]; then
        arch=amd64
    fi

    tailscale_version="1.70.0"

    latest_version=`wget -O- https://pkgs.tailscale.com/stable/ | grep tailscale_ | head -1 | cut -d'_' -f 2`
    if [ "$tailscale_version" != "$latest_version" ]; then
        tailscale_version=$latest_version
    fi

    version="${tailscale_version}_${arch}${endianness}"

    echo "Downloading Tailscale ${version} .."

    echo -e "tailscale_${version}/tailscale" > /usr/cbin/tailscale_${version}_files.txt

    if [ ! -f /usr/cbin/tailscaled ]; then
        echo -e "tailscale_${version}/tailscaled" >> /usr/cbin/tailscale_${version}_files.txt
    fi

    wget -O- https://pkgs.tailscale.com/stable/tailscale_${version}.tgz | tar x -zvf - -C /usr/cbin -T /usr/cbin/tailscale_${version}_files.txt

    mv /usr/cbin/tailscale_$version/* /usr/cbin
    rm -rf /usr/cbin/tailscale_${version}*

    echo "Done!"
fi

/usr/cbin/tailscale "$@"
